apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tooling-demo

resources:
  - namespace.yaml
  - job.yaml
  - networkpolicy.yaml

commonLabels:
  app: tooling-validate
  managed-by: kustomize
  environment: demo

# Configuración común para todos los recursos
commonAnnotations:
  description: "Demo de validación de tooling en Kubernetes"
  repository: "proyectos-aws"
