steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: ¿Dónde estoy y qué veo?
        run: |
          echo "La carpeta actual es:"
          pwd
          echo "Los archivos que veo son:"
          ls -R

      - name: Sincronizar con S3
        run: |
          # Usamos un comodín (*) para que busque la carpeta correcta
          aws s3 sync ./proyecto*-aws/aws-s3-scrum-mi-sitio-1 s3://mi-pagina-scrum-123 --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'