name: Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - 'docs/wiki/**'

jobs:
  upload-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Sync to Wiki
        uses: swift-actions/github-wiki-publish-action@v1
        with:
          path: docs/wiki
          branch: main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
